### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by soaksycustom** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#24]
Bad magic number in .pyc file

I can't fix this issue. I'm already using python 3.11.06

**Comment by TG-ToolsFree** [comment]
Fixed, install the newest version of Python (Python3.12) and it will work.

**Comment by kiko19871312** [comment]
I have latest Python 3.12 and still getting bad magic number in .pyc file, and also getting python: can't open file 'main.py': [Errno 2] No such file or directory
